DB_TABLE = 'stu_schema.cmc_prices'
COLUMNS = ['symbol',
'name',
'price',
'volume_24h',
'volume_change_24h',
'percent_change_1h',
'percent_change_24h',
'percent_change_7d',
'percent_change_30d',
'market_cap',
'market_cap_dominance',
'fully_diluted_market_cap',
'cmc_rank',
'price_last_updated',
'is_active',
'is_fiat',
'circulating_supply',
'total_supply',
'max_supply',
'num_market_pairs']